name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Автодеплой при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Создаём config.js (если нужно)
      - name: Create config.js
        run: |
          echo "const WEB3FORMS_API_KEY = '${{ secrets.WEB3FORMS_API_KEY }}';" > config.js

      # 3️⃣ Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}  # Используем секретный токен
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Ветка для деплоя
          folder: .  # Что деплоить (весь проект)
          clean: true  # Очищает старые файлы перед загрузкой
